version: '3'

services:
  my_app:
    build:
      dockerfile: Dockerfile
      context: ./

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=user
      - SONARQUBE_JDBC_PASSWORD=abc
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/my_database
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    depends_on:
      - sonar_database

  sonar_database:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=my_database
    volumes:
      - sonar_database:/var/lib/postgresql
      - sonar_database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_database:
  sonar_database_data:
  jenkins_home:

